### ISSUE TITLE
'Module not found' when set up under another project

### ISSUE THREAD

**Issue by dlbnco** [schiehll/kerbs#3]
Hey :wave: 

I got into this error today while trying to do a `kerbs` build. The exact same setup used to work before, so I'm struggling to wrap my head around what is actually happening.

Anyway I tried creating a project from scratch and install only `kerbs` but ended up getting into the same error:

# How to reproduce

1. Create a npm project from scratch:

```bash
mkdir someproject && cd someproject && yarn init
```

2. Install and init kerbs
```bash
yarn add --dev kerbs && yarn run kerbs init
```

3. Build kerbs
```bash
yarn run kerbs build
```

```bash
Building kerbs...
/home/dlbnco/labs/someproject/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module '/home/dlbnco/labs/someproject/node_modules/@schiehll/kerbs/node_modules/babel-plugin-preval' from '/home/dlbnco/labs/someproject'
    at Function.resolveSync [as sync] (/home/dlbnco/labs/someproject/node_modules/resolve/lib/sync.js:81:15)
    at resolveStandardizedName (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at /home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-descriptors.js:63:53
    at cachedFunction (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/home/dlbnco/labs/someproject/node_modules/gensync/index.js:244:28)
    at sync (/home/dlbnco/labs/someproject/node_modules/gensync/index.js:84:14)
    at plugins (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at Generator.next (<anonymous>)
    at buildRootChain (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/config-chain.js:68:36)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/partial.js:95:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at Function.<anonymous> (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/index.js:31:43)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/dlbnco/labs/someproject/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/dlbnco/labs/someproject/node_modules/gensync/index.js:84:14)
    at /home/dlbnco/labs/someproject/node_modules/@babel/core/lib/config/index.js:41:61
    at OptionManager.init (/home/dlbnco/labs/someproject/node_modules/@babel/core/lib/index.js:257:36) {
  code: 'MODULE_NOT_FOUND'
}
```

# Thoughts

I also tried cloning the `kerbs` repo itself and everything seemed to work just fine. So I think it might be happening just for npm projects that use `kerbs` as a dependency.

It seems that `kerbs` dependencies are being installed under the parent project's `node_modules`. In the other hand, `kerbs` is importing those dependencies from its own `node_modules`:

https://github.com/schiehll/kerbs/blob/2ed98c3aff71f9763f6c5f5a5c78f7c7f024169c/webpack/webpack.config.js#L8

**Comment by schiehll** [comment]
Hey @dlbnco! Thanks for reporting. I was able to reproduce it, and you are right, it seems to be something related to the paths, which is weird since it was working before...maybe some new behavior from yarn/npm.

I managed to fix the error but there's another one that I was not able to pinpoint yet. I will take a look later and I will let you know here how it went.

**Comment by schiehll** [comment]
@dlbnco I think I've fixed it. Can you try using v2? Same API and everything, just released a major because I changed the way it tries to load some paths and it could be a breaking change if someone is relying on it.

**Comment by dlbnco** [comment]
@schiehll 

Nice, thanks! The build seems to work flawlessly now :)
